# Generated by Django 5.1.3 on 2024-11-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_summernote", "0002_update-help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Defaults to filename, if left blank",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
