# Generated by Django 5.1.3 on 2024-11-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_summernote", "0003_alter_attachment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
